services:
  
  sharm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        YMPD_PORT: ${YMPD_PORT}
        MPD_CLIENT_PORT: ${MPD_CLIENT_PORT}
        MPD_STREAM_PORT: ${MPD_STREAM_PORT}
    container_name: sharm
    restart: unless-stopped
    ports:
      - ${MPD_CLIENT_PORT}:${MPD_CLIENT_PORT}  # MPD Client
      - ${MPD_STREAM_PORT}:${MPD_STREAM_PORT}  # Stream
      - ${YMPD_PORT}:${YMPD_PORT}  # ympd
    volumes:
      - ./media:/var/lib/mpd/music:ro
      - sharm_data:/var/lib/mpd
    healthcheck:
      test: ["CMD-SHELL", "nc -nzv -w 3 127.0.0.1 6600 || exit 1"]
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - sharm-network

volumes:
  sharm_data:

networks:
  sharm-network:
    driver: bridge
 
